# Generated by Django 3.0.3 on 2020-02-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_checkinbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinsheet',
            name='checkinbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Checkinbook'),
        ),
    ]
