# Generated by Django 3.0.3 on 2020-02-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200223_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinsheet',
            name='checkinbook',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Checkinbook'),
        ),
    ]
