# Generated by Django 3.0.3 on 2020-02-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200223_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinsheet',
            name='bt_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
