# Generated by Django 3.0.3 on 2020-02-25 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200224_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('radius', models.IntegerField(default=50)),
                ('checkinsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Checkinsheet')),
            ],
        ),
    ]
