# Generated by Django 3.0.3 on 2020-02-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
