# Generated by Django 3.0.3 on 2020-02-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentitycodeCheckinsheetBond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_code', models.CharField(max_length=20)),
                ('checkinsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Checkinsheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
