# Generated by Django 3.0.3 on 2020-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_useridentitycodecheckinsheetbond'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinsheet',
            name='type',
            field=models.IntegerField(choices=[(0, '面对面快签'), (1, '定位签'), (2, '扫码签'), (3, '口令签'), (4, '链接签'), (5, '无')], default=5),
        ),
    ]
