# Generated by Django 3.0.3 on 2020-02-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_checkinsheet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.IntegerField(default=10000)),
                ('checkinsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Checkinsheet')),
            ],
        ),
    ]
