# Generated by Django 3.0.3 on 2020-02-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinbook',
            name='status',
            field=models.BooleanField(choices=[(0, '进行中'), (1, '已关闭')], default=0),
        ),
        migrations.AlterField(
            model_name='checkinitem',
            name='status',
            field=models.IntegerField(choices=[(0, '待签'), (1, '出勤'), (2, '请假'), (3, '缺勤')], default=0),
        ),
        migrations.AlterField(
            model_name='checkinsheet',
            name='status',
            field=models.BooleanField(choices=[(0, '进行中'), (1, '已关闭')], default=0),
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(0, '就绪'), (1, '进行')], default=0)),
                ('checkinsheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Checkinsheet')),
            ],
        ),
    ]
