# Generated by Django 3.0.3 on 2020-02-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200229_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
