# Generated by Django 3.0.3 on 2020-03-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200301_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wifilist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(0, '目标列表'), (1, '补充列表')], default=0)),
                ('wifilist', models.TextField()),
                ('checkinsheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Checkinsheet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
