# Generated by Django 3.0.3 on 2020-03-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_wifilist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifilist',
            old_name='status',
            new_name='type',
        ),
    ]
